console.log("Starting to make a coffee")
console.log("Grinding coffee beans")
console.log("Boiling water")
console.log("Mixing boiled water with crushed coffee beans")
console.log("Pouring coffee into the cup")
console.log("Pouring some milk into the cup")
console.log("Coffee is ready!")
