let input = require('sync-input');
let cups = input("Write how many cups of coffee you will need:\n");
cups = +cups;
let water = 200 * cups;
let milk = 50 * cups;
let coffeeBeans = 15 * cups;
console.log(`For ${cups} cups of coffee you will need:`);
console.log(`${water} ml of water`);
console.log(`${milk} ml of milk`);
console.log(`${coffeeBeans} g of coffee beans`);
